# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AntBranch
email: coderyi@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  AntBranch开源小组
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://antbranch.com" # the base hostname & protocol for your site
twitter_username: coderyi9
github_username:  antbranch

# Build settings
markdown: kramdown
